version: '3.1'

services:
  app:
    image: 'plus_lab'
    build:
      context: ./app
    ports:
      - "1404:1404"


    container_name: plus_lab_container
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://host.docker.internal:3306/pages_solution

  db:
    container_name: db_plus_lab_container
    image: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysqldocker2022